IPS-9 Revert "Necessary?" <- Yes.
This reverts commit b15678a8aaf1807c42763da60a01fb3fef6819a8.

In file included from src_pEp4ipsec/pEpObjCAdapter/Subprojects/PEPObjCTypeUtils/PEPObjCTypeUtils/PEPIdentity+Engine.m:11:
In file included from src_pEp4ipsec/pEpObjCAdapter/Subprojects/PEPObjCTypeUtils/PEPObjCTypeUtils/PublicHeaders/PEPIdentity+Engine.h:11:
In file included from src_pEp4ipsec/pEpObjCAdapter/Subprojects/PEPObjCTypes/build/include/PEPIdentity.h:11:
src_pEp4ipsec/pEpObjCAdapter/Subprojects/PEPObjCTypes/build/include/PEPEngineTypes.h:14:9: fatal error: 'PEPTransportStatusCode.h' file not found